### ISSUE TITLE
Question about `rnd2`

### ISSUE THREAD

**Issue by crertel** [aabecker/SwarmControlSandbox#1]
https://github.com/aabecker/SwarmControlSandbox/blob/master/exampleControllers/ManualTorqueControl.html#L115

Out of curiosity, is this being done to guarantee a particular distribution of results? Perhaps a normal distribution?

**Comment by sshahrokhi** [comment]
Hi Chris, Actually it is not used in this controller. Just the function exists! I will remove it and update the git.

**Comment by crertel** [comment]
No problem. It might a good candidate for inclusion in the utility libraries. Note that you could perhaps use the Box-Muller transform here ( https://en.wikipedia.org/wiki/Box%E2%80%93Muller_transform ).
